skip_tags: true
clone_depth: 1

os: Visual Studio 2015

environment:
  matrix:
    # - PY_MAJOR_VER: 2
    #   PYTHON_ARCH: "x86_64"
    #   PYTHON: "C:\\Miniconda-x64"

    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"
      PYTHON: "C:\\Miniconda36-x64"

matrix:
  fast_finish: true

install:
  # If there's a newer build queued for the same PR, cancel this one
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda config --add channels omnia --add channels conda-forge
  - conda update --yes --all
  - conda install openmm
  - if "PY_MAJOR_VER"=="2" conda install unittest2

  - ps: wget https://github.com/pandegroup/pdbfixer/archive/master.zip -OutFile pdbfixer.zip
  - 7z x pdbfixer.zip
  - cd pdbfixer-master
  - python setup.py build
  - python setup.py install

  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - python setup.py build

test_script:
  - python -c "import sys; print(sys.version)"
  - cd tests
  - python run_tests.py
  - cd ..