trigger:
  batch: true
  branches:
    include:
      - reorg

pr:
  branches:
    include:
      - reorg

variables:
  condaEnvName: interfacea-ci

stages:
  - template: ci/job_bb.yml
    parameters:
      displayName: Py37
      pyVersion: 3.7

  # - template: ci/job_bb.yml
  #   parameters:
  #     displayName: Py38
  #     pyVersion: 3.8