name: interfacea-dev
# channels:
#   - omnia
dependencies:
  - python
  # library deps to check builds/tests
  - numpy
  - networkx
  # - openmm
  # - pdbfixer

  # dev deps
  - flake8
  - pytest
  - codecov
  - pip
  - pip:
    - pre-commit
    - pytest-cov
