parameters:
  displayName: ''
  pyVersion: ''

stages:
  - stage: "${{ parameters.displayName }}"  # stage names must be unique
    dependsOn: []

    jobs:
      - job:
        workspace:
            clean: all

        strategy:
          matrix:
            linux:
              imageName: 'ubuntu-latest'
            mac:
              imageName: 'macOS-10.14'
            windows:
              imageName: 'vs2017-win2016'

        steps:
          # Define how to call/source conda envs based on Agent.OS
          - script: |
              echo "##vso[task.setvariable variable=activate]call"
            condition: eq( variables['Agent.OS'], 'Windows_NT' )
            name: conda

          - script: |
              echo "##vso[task.setvariable variable=activate]source"
            condition: ne( variables['Agent.OS'], 'Windows_NT' )
            name: conda

          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ parameters.pyVersion }}

          # Modify PATH depending on the OS
          - ${{ if ne(parameters.displayName, 'Windows') }}:
            - script: echo "##vso[task.prependpath]$CONDA/bin"
              displayName: Add Conda to PATH

          - ${{ if eq(parameters.displayName, 'Windows') }}:
            - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
              displayName: Add Conda to PATH

          # Build environment
          - template: setup_conda_env.yml

          # OSX-specific
          - ${{ if eq(parameters.displayName, 'OSX') }}:
            - bash: sudo chown -R $USER $CONDA
              displayName: Take ownership of conda installation

          # Install Package
          - script: |
              $(conda.activate) activate $(condaEnvName)
              python -m pip install -e .
            displayName: Build & Install
