parameters:
  displayName: ''
  vmImage: ''
  steps: []

jobs:
  - job:
    workspace:
        clean: all

    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

    steps:

      # Modify PATH depending on the OS
      - ${{ if ne(parameters.displayName, 'Windows') }}:
        - script: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add Conda to PATH

      - ${{ if eq(parameters.displayName, 'Windows') }}:
        - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
          displayName: Add Conda to PATH

      # Build environment
      - script: |
          conda update -n base conda pip setuptools -y
          conda create --yes --quiet --name $(condaEnvName) python=%PYTHON_VERSION%
          conda env update --name $(condaEnvName) --file devtools/dev-environment.yml
        displayName: Create and Setup Conda Environment
        continueOnError: false

      # Additional custom steps
      - ${{ each step in parameters.steps }}:
        - ${{ each pair in step }}:
            ${{ pair.key }}: ${{ pair.value }}
