parameters:
  displayName: ''
  pyVersion: ''

stages:
  - stage: "${{ parameters.displayName }}"  # stage names must be unique
    dependsOn: []

    jobs:
      - job:
        workspace:
            clean: all

        strategy:
          matrix:
            linux:
              imageName: 'ubuntu-latest'
            mac:
              imageName: 'macOS-10.14'
            windows:
              imageName: 'vs2017-win2016'

        pool:
          vmImage: $(imageName)

        steps:
          # Define how to call/source conda envs based on Agent.OS
          - script: |
              echo "##vso[task.setvariable variable=activate]call"
              echo "##vso[task.prependpath]$env:CONDA\Scripts"
            condition: eq( variables['Agent.OS'], 'Windows_NT' )

          - script: |
              echo "##vso[task.setvariable variable=activate]source"
              echo "##vso[task.prependpath]$CONDA/bin"
            condition: ne( variables['Agent.OS'], 'Windows_NT' )

          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ parameters.pyVersion }}

          # Modify PATH depending on the OS
          - script: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add Conda to PATH
            condition: ne( variables['Agent.OS'], 'Windows_NT' )

          - powershell:
            displayName: Add Conda to PATH
            condition: eq( variables['Agent.OS'], 'Windows_NT' )

          # Build environment
          - script: |
              conda update -n base conda pip setuptools -y
              conda create --yes --quiet --name $(condaEnvName) python=${{ parameters.pyVersion }}
              conda env update --name $(condaEnvName) --file devtools/dev-environment.yml
            displayName: Create and Setup Conda Environment
            continueOnError: false

          # OSX-specific
          - bash: sudo chown -R $USER $CONDA
            displayName: Take ownership of conda installation
            condition: eq( variables['Agent.OS'], 'Darwin' )

          # Package Steps
          # Install
          - script: |
              $ACTIVATE activate $(condaEnvName)
              python -m pip install -e .
            displayName: Building
            continueOnError: false

          # Linter
          - script: |
              $ACTIVATE activate $(condaEnvName)
              flake8 .
            displayName: Linting
            continueOnError: true

          # PyTest (only push to CodeClimate on Linux and master branch commits)
          - script: |
              $ACTIVATE activate $(condaEnvName)
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
            condition: and( eq(variables['Agent.OS'], 'Linux'), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') )
            env:
              GIT_BRANCH: $(Build.SourceBranchName)
              GIT_COMMIT: $(Build.SourceVersion)
              CC_TEST_REPORTER_ID: $(CC_TEST_REPORTER_ID)

          # Run tests for all images/versions
          - script: |
              $ACTIVATE activate $(condaEnvName)
              pytest . --cov=interfacea --cov-report=xml
            displayName: Testing

          - script: |
              $ACTIVATE activate $(condaEnvName)
              ./cc-test-reporter format-coverage -t coverage.py -o coverage/codeclimate.json coverage.xml
              ./cc-test-reporter upload-coverage
            condition: and( eq(variables['Agent.OS'], 'Linux'), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') )
            env:
              GIT_BRANCH: $(Build.SourceBranchName)
              GIT_COMMIT: $(Build.SourceVersion)
              CC_TEST_REPORTER_ID: $(CC_TEST_REPORTER_ID)
