stages:
  - stage:
    displayName: Builder
    dependsOn: []

    jobs:
      - template: job_backbone.yml
        parameters:
          displayName: 'Linux'
          vmImage: 'ubuntu-latest'
          steps:
            - script: |
                source activate $(condaEnvName)
                python setup.py build
                python setup.py install
              displayName: Build & Install

  # These two will run in parallel since they share the same dependency
  # Only run if the Builder step is successful
  - stage:
    displayName: Linter
    dependsOn: Builder
    condition: succeeded('Builder')

    jobs:
      - template: job_backbone.yml
        parameters:
          displayName: 'Linux'
          vmImage: 'ubuntu-latest'
          steps:
            - script: |
                source activate $(condaEnvName)
                flake8 .
              displayName: Run Flake8

  # - stage:
  #     displayName: Tester
  #     dependsOn: Builder
  #     condition: succeeded('Builder')

  #   jobs:
  #     - template: job_backbone.yml
  #       parameters:
  #         displayName: 'Linux'
  #         vmImage: 'ubuntu-latest'
  #         steps:
  #           - script: |
  #               source activate $(condaEnvName)
  #               python setup.py test  # soon to be deprecated, move to pytest
  #             displayName: Run Unit Tests

  # - script: |
  #     conda env remove -n $(condaEnvName)
  #   displayName: Manual Paranoid Cleanup
