jobs:
  - job:
    workspace:
        clean: all

    displayName: Windows
    pool:
      vmImage: 'vs2017-win2016'

    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        # Python38:
        #   python.version: '3.8'

    steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add Conda to PATH

    - template: devtools/setup_conda.yml

    - script: |
        call activate $(condaEnvName)
        conda list
      displayName: Check Environment
      continueOnError: false

    - script: |
        call activate $(condaEnvName)
        python setup.py build
        python setup.py install
      displayName: Build & Install
      continueOnError: false

    - script: |
        conda env remove -n $(condaEnvName)
      displayName: Manual Paranoid Cleanup
