parameters:
  displayName: ''
  vmImage: ''
  jobs: []

jobs:
  - job:
    workspace:
        clean: all

    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

    steps:
    - ${{ each job in parameter.jobs }}:
      - ${{ each pair in job }}:
          ${{ pair.key }}: ${{ pair.value }}
